services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: brian
      POSTGRES_PASSWORD: briankaine
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
